Add data validations
El-Primos/blg317 pull request #71
Opened 2024-12-26 14:58 UTC by kemaltahirbicilioglu

The schema for all the tables has been revised, and data validations have been checked. New data validations have been added to ensure data integrity and consistency. All changes have been commented.

2024-12-26 17:24 UTC, aliemre2023 requested changes
I only review the table_teams.sql

2024-12-26 17:24 UTC, aliemre2023 commented on database/table_creation/table_teams.sql
> +    logo_url TEXT,
if you decided to add name and logo_url column there, also consider the rest of the sql file, because I can't run this file in my computer.

2024-12-26 17:24 UTC, aliemre2023 commented on database/table_creation/table_teams.sql
>      (SELECT arena_id FROM arenas WHERE name = t.arena) AS arena_id
I guess both, city's name and new added name confilicted there, should be defined more clearly.

2024-12-26 17:24 UTC, aliemre2023 commented on database/table_creation/table_teams.sql
> +    logo_url TEXT,
also at the end of the file the logo_url is redefined, sql does not allow me to do this (there are 2 columns with the same name)

2024-12-27 16:55 UTC, aliemre2023 commented
it looks like okay, but :

UPDATE players
SET weight = CAST(weight * 0.453592 AS INT);

UPDATE players
SET height =
    CAST(
        (CAST(substr(height, 1, instr(height, '-') - 1) AS INT) * 30.48 +
         CAST(substr(height, instr(height, '-') + 1) AS INT) * 2.54)
    AS INT);
    
    @umut373  prepare those queries for good looking, in player table we need to use those again.
    
    Also, I prepare some queries for control constrains (for only player table):
    
INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('', 'Doe', 180, 75, '1990-01-01', 'Some College', 1, 'player.png');

INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('John', '', 180, 75, '1990-01-01', 'Some College', 1, 'player.png');

INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('John', 'Doe', -180, 75, '1990-01-01', 'Some College', 1, 'player.png');

INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('John', 'Doe', 180, -75, '1990-01-01', 'Some College', 1, 'player.png');

INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('John', 'Doe', 180, 75, '1899-12-31', 'Some College', 1, 'player.png');

INSERT INTO players (first_name, last_name, height, weight, birth_date, college, country_id, png_name)
VALUES ('John', 'Doe', 180, 75, '1990-01-01', 'Some College', 999, 'player.png');


only last one is creatable (there is no country with id 999), is it a problem?



Site is also work with those queries, I did not see any problem (except admin page)

2024-12-27 18:02 UTC, kemaltahirbicilioglu commented
only last one is creatable (there is no country with id 999), is it a problem?

You’re right, this should have been rejected. SQLite doesn’t enforce foreign key checks by default, so we need to explicitly enable them. I’ve added this to the connection function in our backend, and now invalid data cannot be inserted.

2024-12-27 18:05 UTC, kemaltahirbicilioglu commented
There’s no need to add conversions for height and weight since my code only updates the schema with validations, and the conversions were already handled in the previous table. The data is ready to be inserted without conversion. If we allow users to input different height and weight formats in the future, we can add conversions to the insertion queries.

2024-12-27 18:44 UTC, aliemre2023 approved these changes

2024-12-27 18:44 UTC, merged